services:
  - type: web
    name: pre-is-the-greatest-tracker
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: ADMIN_EMAIL
        value: Prepregardo@gmail.com
      - key: SESSION_SECRET
        generateValue: true
